// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['jquery'], function($) {
    /*
      @name          wrapped-maps-jquery
      @description   A jQuery plugin for Google maps api v3.
      @homepage      https://github.com/ikeikeikeike/wrapped-maps-jquery
      @support_url   https://github.com/ikeikeikeike/wrapped-maps-jquery/issues
    */

    var MAPSMODULE, module_checker, _class;
    module_checker = function() {
      /* Using modules
      */
      try {
        google.maps.Geocoder;
        google.maps.GeocoderStatus;
        google.maps.DirectionsTravelMode;
        google.maps.DirectionsRenderer;
        google.maps.DirectionsService;
        google.maps.DirectionsStatus;
        google.maps.ControlPosition;
        google.maps.InfoWindow;
        google.maps.LatLng;
        google.maps.Map;
        google.maps.Marker;
        google.maps.MapTypeId;
        google.maps.event;
        return jQuery("html");
      } catch (error) {
        throw error;
      }
    };
    try {
      module_checker();
    } catch (error) {
      console.log("[wrapped-maps-jquery] Required module error: " + error + ", Required module in maps.js.");
    }
    /* Main object
    */

    MAPSMODULE = {};
    MAPSMODULE.BaseClass = (function() {

      function BaseClass() {}

      /* Common methods
      */


      /* New object
      */


      BaseClass.prototype.newobj = null;

      BaseClass.prototype.get_options = function() {
        /* Get options
        */
        return this.options;
      };

      BaseClass.prototype.set_options = function(objects) {
        /* Set options by objects
        */

        var key, value, _results;
        _results = [];
        for (key in objects) {
          value = objects[key];
          _results.push(this.options[key] = value);
        }
        return _results;
      };

      BaseClass.prototype.get_newobj = function() {
        /* Get new object
        */
        return this.newobj;
      };

      BaseClass.prototype.set_newobj = function(newobj) {
        return this.newobj = newobj;
        /* Set new object
        */

      };

      BaseClass.prototype.set_value = function(value) {
        /* Set value to a dom
        */

        var _ref, _ref1;
        return ((((_ref = this.el) != null ? _ref.val : void 0) != null) || (((_ref1 = this.el) != null ? _ref1.text : void 0) != null))(value);
      };

      BaseClass.prototype.get_value = function(key) {
        /* Get value of a dom
        */

        var _ref, _ref1;
        return ((((_ref = this.el) != null ? _ref.val : void 0) != null) || (((_ref1 = this.el) != null ? _ref1.text : void 0) != null))();
      };

      BaseClass.prototype.compute = function(num) {
        /* Compute lat and lng
        */
        return Math.round(num * 1000000000) / 1000000000;
      };

      return BaseClass;

    })();
    MAPSMODULE.Event = (function() {

      function Event() {
        return _class.apply(this, arguments);
      }

      /* Wrapped
      */


      _class = (Event.event = google.maps.event);

      /* Initializer
      */


      Event.prototype.on = function(object, event, callback) {
        /* Event listener
        */
        return this.event.addListener(object, event, callback);
      };

      return Event;

    })();
    MAPSMODULE.DirectionsStatue = (function() {
      /* Status Errors
      */

      DirectionsStatue.prototype.statues = [];

      function DirectionsStatue(directions_status) {
        this.directions_status = directions_status != null ? directions_status : google.maps.DirectionsStatus;
        /* Initializer
        */

        this.statues[this.directions_status.INVALID_REQUEST] = 'DirectionsRequest が無効';
        this.statues[this.directions_status.MAX_WAYPOINTS_EXCEEDED] = '経由点がが多すぎます。経由点は 8 以内です。';
        this.statues[this.directions_status.NOT_FOUND] = 'いずれかの点が緯度経度に変換できませんでした。';
        this.statues[this.directions_status.OVER_QUERY_LIMIT] = '単位時間当りのリクエスト制限回数を超えました。';
        this.statues[this.directions_status.REQUEST_DENIED] = 'このサイトからはルートサービスを使用できません。';
        this.statues[this.directions_status.UNKNOWN_ERROR] = '不明なエラーです。もう一度試すと正常に処理される可能性があります。';
        this.statues[this.directions_status.ZERO_RESULTS] = 'ルートを見つけられませんでした。';
      }

      DirectionsStatue.prototype.get_message = function(status) {
        /* Get status message
        */
        return this.statues[status];
      };

      return DirectionsStatue;

    })();
    MAPSMODULE.DirectionsRenderer = (function(_super) {

      __extends(DirectionsRenderer, _super);

      /* Wrapping class
      */


      /* Render options
      */


      DirectionsRenderer.prototype.options = {
        draggable: true
      };

      function DirectionsRenderer(panel_name, options, directions_renderer) {
        this.panel_name = panel_name;
        if (options == null) {
          options = null;
        }
        this.directions_renderer = directions_renderer != null ? directions_renderer : google.maps.DirectionsRenderer;
        /* Initializer
        */

        if (options !== null) {
          this.set_options(options);
        }
        this.set_newobj(new this.directions_renderer(this.options));
        this.set_panel(this.panel_name);
      }

      DirectionsRenderer.prototype.set_map = function(map) {
        /* Set map object
        */
        return this.get_newobj().setMap(map);
      };

      DirectionsRenderer.prototype.set_panel = function(panel_name) {
        if (panel_name == null) {
          panel_name = this.panel_name;
        }
        /* Set panel element name
        */

        return this.get_newobj().setPanel(panel_name);
      };

      DirectionsRenderer.prototype.set_directions = function(results) {
        /* Set directionsService.route response results
        */
        return this.get_newobj().setDirections(results);
      };

      return DirectionsRenderer;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.DirectionsService = (function(_super) {

      __extends(DirectionsService, _super);

      /* Wrapping class
      */


      /* Route options
      */


      DirectionsService.prototype.options = {
        origin: '',
        destination: '',
        waypoints: '',
        optimizeWaypoints: true,
        avoidHighways: true,
        avoidTolls: true,
        travelMode: google.maps.DirectionsTravelMode.DRIVING
      };

      function DirectionsService(options, directions_service, status) {
        if (options == null) {
          options = null;
        }
        this.directions_service = directions_service != null ? directions_service : google.maps.DirectionsService;
        this.status = status != null ? status : MAPSMODULE.DirectionsStatue;
        /* Initializer
        */

        this.set_newobj(new this.directions_service());
        this.status = new this.status();
      }

      DirectionsService.prototype.route = function(options, callback) {
        var self;
        if (options == null) {
          options = this.options;
        }
        /* Request route
        */

        self = this;
        return this.get_newobj().route(options, function(response, status) {
          if (status === google.maps.DirectionsStatus.OK) {
            return callback(response);
          } else {
            return console.log("Directions Service ERROR: " + status + "\n" + (self.status.get_message(status)));
          }
        });
      };

      return DirectionsService;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.Geocorder = (function(_super) {

      __extends(Geocorder, _super);

      /* Wrapping class
      */


      function Geocorder(geocoder, status) {
        this.geocoder = geocoder != null ? geocoder : google.maps.Geocoder;
        this.status = status != null ? status : google.maps.GeocoderStatus;
        /* Initializer
        */

        this.set_newobj(new this.geocoder());
      }

      Geocorder.prototype.address_to_latlng = function(address, callback) {
        /* Convert from address to latlng
        */

        var _this = this;
        return this.get_newobj().geocode({
          'address': address
        }, function(results, status) {
          var m;
          m = status === _this.status.OK ? "ok" : "Geocode was not successful for the following reason: " + status;
          return callback(results, status, m);
        });
      };

      return Geocorder;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.Marker = (function(_super) {

      __extends(Marker, _super);

      /* Wrapping class
      */


      /* Marker options
      */


      Marker.prototype.options = {
        position: null,
        map: null,
        title: null
      };

      function Marker(options, marker) {
        this.options = options;
        this.marker = marker != null ? marker : google.maps.Marker;
        /* Initializer
        */

        this.set_newobj(this.get_new());
      }

      Marker.prototype.get_new = function(options) {
        if (options == null) {
          options = this.options;
        }
        /* Get new object
        */

        return new this.marker(options);
      };

      return Marker;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.InfoWindow = (function(_super) {

      __extends(InfoWindow, _super);

      /* Wrapping class
      */


      InfoWindow.prototype.options = {
        map: null,
        marker: null,
        content: ''
      };

      InfoWindow.prototype.default_template = "<div class=\"\">\n  <div class=\"modal-header modal-header-wrapper\">\n    <h3>{title}</h3>\n  </div>\n  <div class=\"modal-body\">\n    {body}\n  </div>\n</div>";

      function InfoWindow(el_name, optins, infowindow) {
        this.el_name = el_name != null ? el_name : '#infowindow';
        this.optins = optins != null ? optins : null;
        this.infowindow = infowindow != null ? infowindow : google.maps.InfoWindow;
        /* Initializer
        */

        this.el = $(this.el_name);
        if (options !== null) {
          this.set_options(options);
        }
      }

      InfoWindow.prototype.get_template = function() {
        /* Get default template or Element
        */
        if (this.el.is('*')) {
          return this.el.html();
        } else {
          return this.default_template;
        }
      };

      InfoWindow.prototype.render_template = function(title, body) {
        /*
        */

        var template;
        template = template.replace('{title}', title);
        return template.replace('{body}', body);
      };

      InfoWindow.prototype.open = function(map, marker) {
        if (map == null) {
          map = this.options.map;
        }
        if (marker == null) {
          return marker = this.options.marker;
        }
        /* Open info window
        */

      };

      return InfoWindow;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.Map = (function(_super) {

      __extends(Map, _super);

      /* Wrapped
      */


      /* Render element selector
      */


      Map.prototype.el = null;

      /* Renderer options
      */


      Map.prototype.options = {
        zoom: 14,
        scrollwheel: false,
        scaleControl: true,
        center: null,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        scaleControlOptions: {
          position: google.maps.ControlPosition.BOTTOM_CENTER
        }
      };

      function Map(el_name, options, map) {
        this.el_name = el_name != null ? el_name : '#googlemaps';
        if (options == null) {
          options = null;
        }
        this.map = map != null ? map : google.maps.Map;
        /* Initializer
        */

        this.el = $(this.el_name);
        if (options !== null) {
          this.set_options(options);
        }
        this.set_newobj(this.get_new());
      }

      Map.prototype.get_new = function(el, options) {
        if (el == null) {
          el = this.el;
        }
        if (options == null) {
          options = this.options;
        }
        /* Get new map object
        */

        return new this.map(el.get(0), options);
      };

      Map.prototype.get_address = function() {
        /* Address
        */
        return this.el.attr('address');
      };

      Map.prototype.get_title = function() {
        /* Title
        */
        return this.el.attr('title');
      };

      Map.prototype.get_content = function() {
        /* Content
        */
        return this.el.attr('content');
      };

      return Map;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.RouteInfoPanel = (function(_super) {

      __extends(RouteInfoPanel, _super);

      /* Route infomation panel
      */


      /* TOP element
      */


      RouteInfoPanel.prototype.el = null;

      function RouteInfoPanel(el_name) {
        this.el_name = el_name != null ? el_name : '#info_panel';
        /* Initializer
        */

        this.el = $(this.el_name);
      }

      RouteInfoPanel.prototype.set_total_distance = function(results, object) {
        /* Set total distance
        */

        var data, overview_path, routes, _i, _j, _len, _len1, _ref, _ref1;
        data = '';
        _ref = results.routes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          routes = _ref[_i];
          _ref1 = routes.overview_path;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            overview_path = _ref1[_j];
            data += "" + (this.compute(overview_path.lng())) + "," + (this.compute(overview_path.lat())) + "\n";
          }
        }
        return this.set_value(data);
      };

      return RouteInfoPanel;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.RouteDirectionsPanel = (function(_super) {

      __extends(RouteDirectionsPanel, _super);

      /* Route result panel
      */


      /* TOP element
      */


      RouteDirectionsPanel.prototype.el = null;

      /* Rirections options
      */


      RouteDirectionsPanel.prototype.options = {
        total: '#total'
      };

      function RouteDirectionsPanel(el_name, options) {
        this.el_name = el_name != null ? el_name : '#directions_panel';
        if (options == null) {
          options = null;
        }
        /* Initializer
        @param {String} el_name - Top element name.
        @param {Object} options - options.
        
        .. Options, e.g. ::
        
            options =
              total: '#total'
        */

        this.el = $(this.el_name);
      }

      RouteDirectionsPanel.prototype.set_total_distance = function(results, object) {
        /* Set total distance
        */

        var legs, total, _i, _len, _ref;
        total = 0;
        _ref = results.routes[0].legs;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          legs = _ref[_i];
          total += legs.distance.value;
        }
        return this.el.find(this.options.total).text(total / 1000 + " km");
      };

      return RouteDirectionsPanel;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.RouteControlPanel = (function(_super) {

      __extends(RouteControlPanel, _super);

      /* Route controller panel
      */


      /* TOP element
      */


      RouteControlPanel.prototype.el = null;

      /* Controller options
      */


      RouteControlPanel.prototype.options = {
        focus: {
          input: true,
          next: true
        },
        start: {
          point: '#start_point',
          checked: '#start_checked'
        },
        end: {
          point: '#end_point',
          checked: '#end_checked'
        },
        way: {
          point: '#way_point',
          checked: '#way_checked',
          nontollway: '#way_nontollway',
          nonhighway: '#way_nonhighway'
        },
        event: {
          route: {
            id: '#click_route',
            event: {
              click: function(event, cls) {}
            }
          },
          clearaddr: {
            id: '#click_clearaddr',
            event: {
              click: function(event, cls) {}
            }
          }
        }
      };

      function RouteControlPanel(el_name, options) {
        this.el_name = el_name != null ? el_name : '#control_panel';
        if (options == null) {
          options = null;
        }
        /* Initializer
        @param {String} el_name - Top element name.
        @param {Object} options - Contoller options.
        
        .. Options, e.g. ::
        
            options =
              focus:
                input: true
                next: true
              start:
                point: '#start_point'
                checked: '#start_checked'
              end:
                point: '#end_point'
                checked: '#end_checked'
              way:
                point: '#way_point'
                checked: '#way_checked'
                nontollway: '#way_nontollway'
                nonhighway: '#way_nonhighway'
        
              ## event or event ##
              event:
                route: '#click_route'
                clearaddr: '#click_clearaddr'
              event:
                route:
                  id: '#click_route'
                  event:
                    click: (event, cls) ->
                clearaddr:
                  id: '#click_clearaddr'
                  event:
                    click: (event, cls) ->
                    dblclick: (event, cls) -> # TODO: Multiple event, Not implemention.
        */

        this.el = $(this.el_name);
        this.set_selectors(options || this.options);
        if (this.options.focus.input === true) {
          this.push_value();
        }
      }

      RouteControlPanel.prototype.set_selectors = function(selectors) {
        /* Controller selectors
        */

        var end, start, way;
        start = selectors != null ? selectors.start : void 0;
        start.checked;
        start.point;
        end = selectors != null ? selectors.end : void 0;
        end.checked;
        end.point;
        way = selectors != null ? selectors.way : void 0;
        way.checked;
        return way.point;
      };

      RouteControlPanel.prototype.generate_html = function(selectors) {
        /* Generate control panel
        */

      };

      RouteControlPanel.prototype.get_selector = function(key) {
        var i, op, _i, _len, _ref;
        op = this.options;
        _ref = key.split(".");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          op = op[i];
        }
        return op;
      };

      RouteControlPanel.prototype.get_element = function(key) {
        /*
        */
        return $(this.get_selector(key));
      };

      RouteControlPanel.prototype.set_value = function(key, value) {
        /* Set value to a panel
        */

        var elm;
        elm = this.get_element(key);
        return (((elm != null ? elm.val : void 0) != null) || ((elm != null ? elm.text : void 0) != null))(value);
      };

      RouteControlPanel.prototype.get_value = function(key) {
        /* Get value of a panel
        */

        var elm;
        elm = this.get_element(key);
        return (((elm != null ? elm.val : void 0) != null) || ((elm != null ? elm.text : void 0) != null))();
      };

      RouteControlPanel.prototype.set_value_tostart = function(value) {
        /*
        */
        return this.set_value('start.point', value);
      };

      RouteControlPanel.prototype.set_value_toend = function(value) {
        /*
        */
        return this.set_value('end.point', value);
      };

      RouteControlPanel.prototype.set_value_toway = function(value) {
        /*
        */
        return this.set_value('way.point', "" + (this.get_value('way.point')) + value + "\n");
      };

      RouteControlPanel.prototype.set_point = function(latlng, object) {
        if (object == null) {
          object = null;
        }
        /* Set latLng to dom and next focus.
        */

        if (is_checked('start.checked')) {
          this.set_value_tostart(latlang);
          return this.next_focus('start.point');
        } else if (is_checked('end.checked')) {
          this.set_value_toend(latlang);
          return this.next_focus('end.point');
        } else if (is_checked('way.checked')) {
          return this.set_value_toway(latlang);
        } else {
          return console.log('[RouteControlPanel.set_point] Not checked error.');
        }
      };

      RouteControlPanel.prototype.next_focus = function(key) {
        /* Next focus for input text
        */
        if (this.options.focus.next) {
          return this.get_element(key === "start.point" ? "end.point" : key === "end.point" ? "way.point" : void 0).focus();
        }
      };

      RouteControlPanel.prototype.is_checked = function(key) {
        /* Check push value element
        */

        var elm;
        elm = this.get_element(key);
        if (elm.checked) {
          return true;
        } else if (this._push_value_el === null) {
          return false;
        } else if (this._push_value_el.is(elm)) {
          return true;
        } else {
          return false;
        }
      };

      /* Current fucus element
      */


      RouteControlPanel.prototype._push_value_el = null;

      RouteControlPanel.prototype.push_value = function() {
        /* Set current focus
        */

        var self;
        self = this;
        this.get_element('start.point').focus(function() {
          return self._push_value_el = $(this);
        }).blur(function() {
          return self._push_value_el = null;
        });
        this.get_element('end.point').focus(function() {
          return self._push_value_el = $(this);
        }).blur(function() {
          return self._push_value_el = null;
        });
        return this.get_element('way.point').focus(function() {
          return self._push_value_el = $(this);
        }).blur(function() {
          return self._push_value_el = null;
        });
      };

      RouteControlPanel.prototype._get_objkey = function(object) {
        /* For one object
        */

        var k, v;
        return ((function() {
          var _results;
          _results = [];
          for (k in object) {
            v = object[k];
            _results.push(k);
          }
          return _results;
        })())[0];
      };

      RouteControlPanel.prototype._get_objvalue = function(object) {
        /* For one object
        */

        var k, v;
        return ((function() {
          var _results;
          _results = [];
          for (k in object) {
            v = object[k];
            _results.push(v);
          }
          return _results;
        })())[0];
      };

      RouteControlPanel.prototype.on = function(object) {
        if (object == null) {
          object = null;
        }
        /* Utility
        */

        return $(object.id).on(object.event, {
          maincallback: object.maincallback,
          usercallback: object.usercallback
        }, object.method);
      };

      RouteControlPanel.prototype.add_route_event = function(object) {
        var route;
        if (object == null) {
          object = null;
        }
        /* Add events listener
        */

        if (!this.options.event) {
          return this.on({
            id: this.options.event.route,
            event: 'click',
            method: this.on_route,
            callback: {
              main: callback,
              user: null
            }
          });
        } else {
          route = this.options.event.route;
          return this.on({
            id: route.id,
            event: this._get_objkey(route),
            method: this.on_route,
            callback: {
              main: callback,
              user: this._get_objvalue(route)
            }
          });
        }
      };

      RouteControlPanel.prototype.add_clearaddr_event = function(object) {
        var clearaddr;
        if (object == null) {
          object = null;
        }
        /* Add events listener
        */

        if (!this.options.event) {
          return this.on({
            id: this.options.event.clearaddr,
            event: 'click',
            method: this.on_clearaddr,
            callback: {
              main: callback,
              user: null
            }
          });
        } else {
          clearaddr = this.options.event.clearaddr;
          return this.on({
            id: clearaddr.id,
            event: this._get_objkey(clearaddr),
            method: this.on_clearaddr,
            callback: {
              main: callback,
              user: this._get_objvalue(clearaddr)
            }
          });
        }
      };

      RouteControlPanel.prototype.on_clearaddr = function(event) {
        /*
        */
        if (event != null) {
          event.usercallback();
        }
        return event != null ? event.maincallback() : void 0;
      };

      RouteControlPanel.prototype.on_route = function(event) {
        /* Route search request
        */

        var end, hw, start, toll, wats, waypts, _i, _len, _ref;
        start = this.get_value('start.point');
        end = this.get_value('end.point');
        hw = this.get_element("way.nonhighway").checked ? true : false;
        toll = this.get_element("way.nontollway").checked ? true : false;
        waypts = [];
        _ref = this.get_value("way.point").split("\n");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          wats = _ref[_i];
          if (wats !== '') {
            waypts.push({
              location: wats,
              stopover: true
            });
          }
        }
        event.control_panel = {
          options: {
            start: start,
            end: end,
            hw: hw,
            toll: toll,
            waypts: waypts
          }
        };
        if (event != null) {
          event.usercallback(event, this);
        }
        return event != null ? event.maincallback(event, this) : void 0;
      };

      return RouteControlPanel;

    })(MAPSMODULE.BaseClass);
    MAPSMODULE.RenderRouteMap = (function(_super) {

      __extends(RenderRouteMap, _super);

      /* Route map class
      */


      /* Control panel
      */


      RenderRouteMap.prototype.control_panel = MAPSMODULE.RouteControlPanel;

      /* Result panel
      */


      RenderRouteMap.prototype.direct_panel = MAPSMODULE.RouteDirectionsPanel;

      /* Info panel
      */


      RenderRouteMap.prototype.info_panel = MAPSMODULE.RouteInfoPanel;

      /* Direction Renderer object
      */


      RenderRouteMap.prototype.direct_render = MAPSMODULE.DirectionsRenderer;

      /* Direction Service object
      */


      RenderRouteMap.prototype.direct_service = MAPSMODULE.DirectionsService;

      /* Map object
      */


      RenderRouteMap.prototype.map = MAPSMODULE.Map;

      /* Marker object
      */


      RenderRouteMap.prototype.marker = MAPSMODULE.Marker;

      /* InfoWindow object
      */


      RenderRouteMap.prototype.infowindow = MAPSMODULE.InfoWindow;

      /* Event object
      */


      RenderRouteMap.prototype.event = MAPSMODULE.Event;

      /* Geocorder object
      */


      RenderRouteMap.prototype.geocorder = MAPSMODULE.Geocorder;

      function RenderRouteMap(options) {
        if (options == null) {
          options = null;
        }
        this.click_event_receiver_formap = __bind(this.click_event_receiver_formap, this);

        this.click_event_receiver_formarker = __bind(this.click_event_receiver_formarker, this);

        this.click_event_receiver_clearaddr = __bind(this.click_event_receiver_clearaddr, this);

        this.click_event_receiver_route = __bind(this.click_event_receiver_route, this);

        /* Initializer
        @param {String|Object} place - Address{String} or Google latlng{Object}.
        @param {Object} options - Options for rendering map.
        
        .. Options, e.g. ::
        
            options =
              direct_panel:
                obj: new RouteDirectionsPanel("#directions_panel")
                name: '#directions_panel'
                options: null
              control_panel:
                obj: new RouteControlPanel("#control_panel")
                name: '#direct_panel'
                options: {}
              info_panel:
                obj: new RouteInfoPanel("#info_panel")
                name: '#info_panel'
                options: {}
              direct_render:
                obj: new DirectionsRenderer('#renderer')
                name: '#renderer'
                options: {}
              map:
                obj: new Map("#map")
                name: '#map'
                options: {}
        */

        this.set_option_class(options, 'direct_panel');
        this.set_option_class(options, 'control_panel');
        this.set_option_class(options, 'info_panel');
        this.set_option_class(options, 'direct_render');
        this.set_option_class(options, 'map');
        this.set_option_class(options, 'geocorder');
        this.place = options != null ? options.place : void 0;
      }

      RenderRouteMap.prototype.set_option_class = function(options, key) {
        /* Set class to attribute
        */

        var name, objs, objs_obj, v;
        objs = options != null ? options[key] : void 0;
        objs_obj = (objs != null ? objs.obj : void 0) || null;
        if (objs_obj !== null) {
          return this[key] = objs_obj;
        } else {
          name = (objs != null ? objs.name : void 0) || null;
          if (name === null) {
            console.log("[RenderRouteMap.constructor] Arguments error: options." + key + ".name is require. (" + key + ".name is " + name + ")");
          }
          return this[key] = new (((function() {
            var _results;
            _results = [];
            for (v in objs != null ? objs.options : void 0) {
              _results.push(v);
            }
            return _results;
          })()).length ? this[key](name, objs.options) : name ? this[key](name) : this[key]);
        }
      };

      RenderRouteMap.prototype.run = function(options) {
        var _this = this;
        if (options == null) {
          options = {};
        }
        /* Render map
        */

        return this.get_latlng(options != null ? options.place : void 0, function(results, status, message) {
          /* Current latlng
          */

          var latlng;
          latlng = results[0].geometry.location;
          console.log('[run] Request address: ', results, status, message);
          _this.set_map();
          _this.set_direct_panel();
          return _this.open_infowindow(latlng);
          /*
                  # @event.on @map.get_newobj() 'click', @click_event_receiver_formap
          
                    var myOptions = {
                        zoom: 14,
                        scrollwheel: false,
                        scaleControl: true,
                        center: latlng,
                        mapTypeId: google.maps.MapTypeId.ROADMAP,
                        scaleControlOptions: {position: google.maps.ControlPosition.BOTTOM_CENTER}
                    }
          
                    map = new google.maps.Map(document.getElementById("googlemaps"), myOptions);
                    directionsDisplay.setMap(map);
                    directionsDisplay.setPanel(document.getElementById("directions_panel"));
          
                    marker = new google.maps.Marker({
                      position: latlng,   // マーカーの位置
                      map: map,   // 表示する地図
                      title: title   // ロールオーバー テキスト
                    });
          
                    // 吹き出しを作成します
                    infowindow = new google.maps.InfoWindow({content: content});
          
                    // 吹き出しをオープンします
                    infowindow.open(map, marker);
          
                    // クリックしたときに吹き出しがオープンするイベントを定義します
                    google.maps.event.addListener(marker, 'click', function() {
                      infowindow.open(map, marker);
                    });
          
                    google.maps.event.addListener(map, 'click', function(mouseEvent) {
                        setPoints(map, mouseEvent.latLng);
                    });
                    google.maps.event.addListener(directionsDisplay, 'directions_changed', function() {
                        computeTotalDistance(directionsDisplay.directions);
                    });
          */

        });
      };

      RenderRouteMap.prototype.get_latlng = function(place, callback) {
        if (place == null) {
          place = this.place;
        }
        /* Get latlng
        */

        return this.geocorder.address_to_latlng(place || this.map.get_address(), function(results, status, message) {
          return callback(results, status, message);
        });
      };

      RenderRouteMap.prototype.get_marker = function(latlng, title, map) {
        if (title == null) {
          title = this.map.get_title();
        }
        if (map == null) {
          map = this.map.get_newobj();
        }
        /* Get marker object
        */

        return new this.marker({
          positoin: latlng,
          title: title,
          map: map
        });
      };

      RenderRouteMap.open_info = function(latlng, map) {
        var marker;
        if (map == null) {
          map = this.map.get_newobj();
        }
        /* Open info window
        */

        marker = this.get_marker(latlng);
        return this.infowindow.open(map, marker);
      };

      RenderRouteMap.prototype.set_map = function(map) {
        if (map == null) {
          map = this.map.get_newobj();
        }
        /* Set map
        */

        return this.direct_render.set_map(map);
      };

      RenderRouteMap.prototype.set_direct_panel = function(direct_panel_el) {
        if (direct_panel_el == null) {
          direct_panel_el = this.direct_panel.el;
        }
        /* Set panel
        */

        if (direct_panel_el.is('*')) {
          return this.direct_render.set_panel(direct_panel_el.get(0));
        } else {
          return console.log("[RenderRouteMap.set_direct_panel] Arguments error: (direct_panel_el is " + direct_panel_el + ")");
        }
      };

      RenderRouteMap.prototype.click_event_receiver_route = function(event, cls) {
        /* From control panel
        */

      };

      RenderRouteMap.prototype.click_event_receiver_clearaddr = function(event, cls) {
        /* From control panel
        */

      };

      RenderRouteMap.prototype.click_event_receiver_formarker = function(event) {
        /* Mouse event receiver
        */
        return this.infowindow.open(this.map.get_newobj(), this.marker.get_newobj());
      };

      RenderRouteMap.prototype.click_event_receiver_formap = function(event) {
        /* Mouse event receiver
        */
        return this.control_panel.set_point(event.latLng, this.map.get_newobj());
      };

      RenderRouteMap.prototype.directions_changed_receiver_formap = function(event) {
        /* Directions changed event receiver
        */

        var newobj;
        newobj = this.direct_render.get_newobj();
        this.direct_panel.set_total_distance(newobj.directions, newobj);
        return this.info_panel.set_total_distance(newobj.directions, newobj);
      };

      return RenderRouteMap;

    })(MAPSMODULE.BaseClass);
    return MAPSMODULE;
  });

}).call(this);
